name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # Remplace cette URL par ton flux RSS (Medium, Dev.to, WordPress, ou même YouTube)
          feed_list: "https://medium.com/feed/@ton_pseudo_medium"
